### ISSUE TITLE
Error with maps showing.

### ISSUE THREAD

**Issue by tiakindele** [CMPUT301F17T23/routineKeen#2]
I've spent hours trying to make the maps show. I keep getting these errors but I've checked the API keys in 
- **app/src/debug/res/values/google_maps_api.xml**,
- **app/src/release/res/values/google_maps_api.xml** and 
- **app/src/main/AndroidManifest.xml**

Starting to wonder if it's an issue with my device/virtual device.

//pictures attached
<img width="301" alt="screen shot 2017-11-24 at 10 48 31 am" src="https://user-images.githubusercontent.com/18653558/33220614-def82c90-d106-11e7-8275-ab862c03c595.png">
<img width="1212" alt="screen shot 2017-11-24 at 10 50 53 am" src="https://user-images.githubusercontent.com/18653558/33220615-df0a43b2-d106-11e7-8a9f-16e7687c8a06.png">

**Comment by hughboi** [comment]
tolu fixed it
