### ISSUE TITLE
HabitProgressActivity crashing app

### ISSUE THREAD

**Issue by aridgway120** [CMPUT301F17T23/routineKeen#3]
App crashes when you click the back button in the top left corner of HabitProgressActivity.

Issue does not occur when using the device's built-in back button.

**Comment by hughboi** [comment]
I was able to fix this using this [stackoverflow post](https://stackoverflow.com/questions/6554317/savedinstancestate-is-always-null) after a bit of searching. It's not the most robust solution, but it works pretty great for now.
